### ISSUE TITLE
`merge` should not use rebase

### ISSUE THREAD

**Issue by jamiew** [jamiew/git-friendly#26]
Per conversation on best practices with @paulirish

`merge` using rebase on local-only branches causes drama with integration branch workflow. In these cases I'm forced to use vanilla "git merge" instead of just "merge". 

The rare gain from using rebase to avoid merge commits is not worth the occasional merge-rebase-hell it causes

**Comment by sapegin** [comment]
Do we still want this fire years later? ;-)

**Comment by jamiew** [comment]
I think this is becoming git-default in 2.0, right? And is already a best practice... so happy to close :) Re-open if I got anything wrong
