### ISSUE TITLE
`branch` does not take advantage of git-completion

### ISSUE THREAD

**Issue by jamiew** [jamiew/git-friendly#35]
https://github.com/git/git/blob/master/contrib/completion/git-completion.bash

I want to go to there

If you have homebrew on a mac, run:

```
source /usr/local/etc/bash_completion.d/git-completion.bash
```

And now typing `git checkout mybr[tab]` turns into `git checkout mybranch`

git-friendly `branch` should take advantage

**Comment by jamiew** [comment]
3 years later this is my favorite wishlist item for git-friendly. 

I still use `git checkout` specifically for the completion, and just use `branch` for making new branches

**Comment by sapegin** [comment]
Looks like it’s quite easy with zsh:

```
fpath=($(brew --prefix)/share/zsh/functions $fpath)
autoload -Uz _git && _git
compdef __git_branch_names branch
```

**Comment by jamiew** [comment]
Oh that's awesome. I found something similar for `bash`. Do you think it's worth adding?

**Comment by sapegin** [comment]
I’ll add it ;-)
