### ISSUE TITLE
Images in Readme disappears

### ISSUE THREAD

**Issue by sapegin** [jamiew/git-friendly#41]
![](http://wow.sapegin.me/image/2V3I153l3U2N/Image%202014-07-25%20at%205.59.22%20%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%20%D0%BF%D0%BE%D0%BB%D1%83%D0%B4%D0%BD%D1%8F.png)

**Comment by sapegin** [comment]
Hey it was year ago :disappointed_relieved:

**Comment by jamiew** [comment]
You are awesome, thank you.

**Comment by jamiew** [comment]
My old jamiedubs.com host got wiped out and I actually had lost all these
images :\

**Comment by sapegin** [comment]
Luckily we have the Internet Archive ;-)
