### ISSUE TITLE
`push` is broken, but i cant debug it :/

### ISSUE THREAD

**Issue by TCMiranda** [jamiew/git-friendly#42]
Hey, I am using fedora and nested repos.

`push` is freezing, and does not sends anything to my output...

How can I debug this problem and improve this issue?

Thanks!

**Comment by TCMiranda** [comment]
Oh, one thing is that the push actually works, but the command freezes.

**Comment by sapegin** [comment]
I have the same on OS X sometimes. Probably when my wifi connection is unstable.

**Comment by jamiew** [comment]
Huh interesting. Do you have an example of where the output gets to?

Offhand I wonder if `pbclip` or `xclip` are hanging

**Comment by TCMiranda** [comment]
Uhmm, sorry, I am not sure.. Although, I would be happy to help. Problem is that I don't know how I can debug it for you.

What happens exactly is that the commit is successfully pushed, but the command gets frozen.

```
$: push
...nothing more happens
```

Also, I dont have `pbclip`, but I do have `xclip`

**Comment by jamiew** [comment]
Do you have unreliable Internet? per what @sapegin mentioned

I would imagine you'd at least see a git error if that was it... 

Are you in Linux? Do you have `tput` installed? That's referenced at the top of the script, before anything with `git`

**Comment by TCMiranda** [comment]
Yes I do, sometimes I work under my mobile connection, and its probably because of that.. Any way to handle those connection issues? Or even test if that is the case?

I do have tput installed, also

**Comment by jamiew** [comment]
When I disable my networking entirely it aborts correctly. I think issue is maybe that it's sort of connecting? Hard to say without more debug output

**Comment by jamiew** [comment]
@TCMiranda are you still having this issue? Cleaning up open issues

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen if you still have this issue.
