### ISSUE TITLE
Pull after branch change?

### ISSUE THREAD

**Issue by sapegin** [jamiew/git-friendly#62]
For me that would be desired behavior most of the time: to pull latest changes after I switch to another branch. What do you think?

**Comment by sapegin** [comment]
I’ve just made an alias to do that:

https://github.com/sapegin/dotfiles/blob/316caa7264154e391bcc1bddfbdd23994bf744e9/zsh/aliases.zsh#L70-L77

**Comment by jamiew** [comment]
Oh nice, I like the alias solution. I can't think of any offhand but I can imagine cases where you might want to switch branches but NOT pull, so forcing it would be inconvenient since you'd need to crack open `reflog` and figure out where you were etc

**Comment by sapegin** [comment]
Here is the correct version of an alias: https://github.com/sapegin/dotfiles/blob/master/bin/br
