### ISSUE TITLE
Weird push behavior

### ISSUE THREAD

**Issue by sapegin** [jamiew/git-friendly#63]
`push` says “Git says everything is up-to-date!” even on failure.

`push` tries to do:

```
❯ git push --set-upstream  origin master
Branch 'master' set up to track remote branch 'master' from 'origin'.
Everything up-to-date
```

And exits after that thinking that everything is fine. But if run after that:

```
❯ git push
To <...>
 ! [rejected]                qa_customer_answer_form_pt_13703944 -> qa_customer_answer_form_pt_13703944 (non-fast-forward)
error: failed to push some refs to 'git@<..>'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by sapegin** [comment]
Looks like it was caused by `git branch --set-upstream-to=origin/master` in our deployment process.

**Comment by jamiew** [comment]
Huh, so your upstreams were mismatched?

I've been running into a few weird cases like this too lately, where `push` was either not correctly identifying current state, or copied weird junk into the post-commit message copy (certainly another argument against that)

**Comment by sapegin** [comment]
I'm going to close it for now, since it was an issue on my side and I'm not sure how to protect from it.
