### ISSUE TITLE
Clone script

### ISSUE THREAD

**Issue by sapegin** [jamiew/git-friendly#68]
I'm experimenting with git clone script that will `cd` into the repo directory. The script itself is simple:

```bash
#!/usr/bin/env bash

repo=$1
clonepath=$2

if [ -z $clonepath ]; then
    clonepath=$(basename $repo .git)
fi

git clone $repo $clonepath

cd $clonepath
```

But to make `cd` works, you need an alias in your shell like this:

```bash
alias clone="source clone"
```

What do you think? Will this fit git-friendly?

**Comment by jamiew** [comment]
Huh interesting. This is simple enough that my gut is that it's better off as a shell or gitconfig alias... that's basically how git-friendly got started :)

Are you using it pretty regularly? Maybe we check with some others for opinions?

**Comment by sapegin** [comment]
Yeah, I often clone repos — for example demos for bugs, so I often use a folder name like `kjalfjdslfkjsd` because I likely have a few other folders with other forks of the same repo ;-)

But yeah, lets wait for other opinons.
