### ISSUE TITLE
GitHub organization

### ISSUE THREAD

**Issue by sapegin** [jamiew/git-friendly#83]
Since we have two repositories now, I think it would make sense to move both to a GitHub organization. What do you think?

**Comment by jamiew** [comment]
I'm mildly disinclined just because I've created and abandoned more orgs than I'd like to admit, but this project is definitely something the two of us seem to use every day :) would you prefer it since it makes things more official/detached from my personal account?

**Comment by sapegin** [comment]
Yes, and also Homebrew instructions would look much nicer ;-)

**Comment by jamiew** [comment]
@sapegin sounds good to me, creating one now :)

**Comment by sapegin** [comment]
Yay! 💥
